### ISSUE TITLE
LED Demo not showing LEDs in order 

### ISSUE THREAD

**Issue by Elroyrivers** [magicjellybeanfpga/MiniStar#3]
When I follow demo and run the LED demo, the LEDs do not show up in the correct order. 

I followed the guide and used pins 48~35 but when setting pin 01 within the CST file for "gpio_io[7]" I got the following error message:

![cst pin 01  error](https://user-images.githubusercontent.com/91693648/135508201-6ad9206d-34cb-4a43-8f0b-c6ce28c9f672.JPG)

ERROR  (CT1113) : "C:\Users\Andrew Dudaronek\Desktop\MiniStar-main (2)\MiniStar-main\projects\Led Demo\led_run\fpga_led\src\top.cst":9 | Can't find pad location '01' in current package

**Comment by magicjellybeanfpga** [comment]
Hey Elroyrivers, 

Thanks for posting and finding this! 

Looks like the default pin numbers of 48~35 will not result in the LEDs lighting up in the correct order as the demo video shows. 

We went ahead and updated the documentation and the .cst file so it defaults to this pin order. You will just need to match your jumper cables in this order when running the project: 

<img width="582" alt="Ministar pin led" src="https://user-images.githubusercontent.com/81582905/135666033-f436308c-b58e-4f1a-ac87-a64bdb606f69.png">

You also can edit the .cst file and switch around your pins if you wish to see the LEDs lighting up in a different order. 

-MJB team
